version: '3.8'

services:
  postgres-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=urls_db
      - POSTGRES_USER=urls_admin
      - POSTGRES_PASSWORD=urls_admin
